// Generated by LiveScript 1.3.0
var request;
request = require('request');
request({
  method: 'POST',
  uri: 'https://www.ethercalc.org/_/ckiarss5uv',
  body: 'foo, bar, foobar, boo'
}, function(err, res, body){
  return console.log(body);
}).setHeader({
  'content-type': 'text/csv'
});
