// Generated by LiveScript 1.2.0
(function(){
  var fs, Brainfuck;
  fs = require('fs');
  Brainfuck = require('./bf');
  fs.readFile('./hello.bf', function(err, data){
    var x$, bf;
    if (err) {
      throw err;
    }
    x$ = bf = Brainfuck();
    x$.output = function(it){
      return process.stdout.write(it);
    };
    x$.exec(data.toString());
    return x$;
  });
}).call(this);
