// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    entry: './index.js',
    output: {
      path: __dirname,
      filename: 'build.js'
    },
    amd: {
      jQuery: true
    }
  };
}).call(this);
